version: xxHash-{branch}-{build}

test: off

before_build:
  - choco install opencover.portable
  - choco install codecov

install:
  - ps: $env:DOTNET_BUILD_VERSION = $env:APPVEYOR_BUILD_NUMBER
  
build_script:
  - cmd: build.cmd
  
artifacts:
  - path: artifacts\*.nupkg
  
test_script:
  - OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test src/Standart.Hash.xxHash.Test" -output:coverage.xml -oldstyle -filter:"+[Standart*]* -[*.Test]*"
  - codecov -f "coverage.xml"
  
deploy:
  provider: NuGet
  api_key:
    secure: $env:NUGET_TOKEN
  skip_symbols: true
  artifact: /.*\.nupkg/